Add deepEqualAdded #18
GrosSacASac/utilsac pull request #25
Opened 2019-10-09 21:45 UTC by jmeline

A little more cleanup is expected but here is the first draft of this.

2019-10-09 21:46 UTC, jmeline commented on deep.js
> +const validateArray = (a,b) => {
I found that I was doing the same array looping in multiple places. I suck with naming and I am happy to take suggestions for an alternate name.

2019-10-09 21:47 UTC, jmeline commented on package.json
> -    "rules": {
I can probably leave this in.

2019-10-09 22:08 UTC, GrosSacASac requested changes
use 4 spaces for indentation

always include extension inside import

other than that it's ok (we can always do incremental improvements later)

2019-10-09 22:09 UTC, GrosSacASac requested changes

2019-10-09 22:09 UTC, GrosSacASac commented on tests/specification/deepEqual.js
> +import { deepEqual, deepEqualAdded } from "../../deep";
include extension

2019-10-09 22:24 UTC, jmeline commented
Addressed concerns. If there are any others, let me know.

2019-10-09 22:31 UTC, merged

2019-12-18 16:06 UTC, GrosSacASac commented
follow up issue https://github.com/GrosSacASac/utilsac/issues/31